language: php

php:
  - 5.3.3

services:
  - Redis
  - Memcached

notifications:
  irc: "irc.freenode.org#molajo"
  email: amystephen@gmail.com


before_script: php .dev/travis-setup.php apc

script:
 phpunit  -c .dev/phpunit.xml
